Client/Models/ErrorViewModel.cs
namespace Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/ViewModels/JwtTokenVM.cs
namespace Client.ViewModels
{
    public class JwtTokenVM
    {
        public string StatusCode { get; set; }
        public string Token { get; set; }
        public string Message { get; set; }
    }
}

Client/ViewModels/LoginVM.cs
namespace Client.ViewModels
{
    public class LoginVM
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Client/Controllers/AccountController.cs
using API.Models;
using Client.Base;
using Client.Repositories.Data;
using Client.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class AccountController : BaseController<User, AccountRepository, int>
    {
        private readonly AccountRepository repository;
        public AccountController(AccountRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        /*[HttpPost]
        public JsonResult Register(RegisterVM registerVM)
        {
            var result = repository.Register(registerVM);
            return Json(result);
        }*/
        [HttpPost]
        public async Task<JsonResult> Login([FromBody]LoginVM loginVM)
        {
            var result = await repository.Auth(loginVM);
            if (result.Token != null)
            {
                HttpContext.Session.SetString("JWToken", result.Token);

            }
            return Json(result);
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
    }
}

Client/Controllers/AdminCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminCategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/AdminOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminOrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/AdminPaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminPaymentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/AdminProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/AdminUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminUserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/HomeController.cs
using System.Diagnostics;
using Client.Models;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Forbidden()
        {
            return View("Forbidden");
        }
        public IActionResult Unauthorization()
        {
            return View("Unauthorized");
        }
        public IActionResult NotFound404()
        {
            return View("NotFound");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/HomeUserController.cs
using System.Diagnostics;
using Client.Models;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class HomeUserController : Controller
    {
        private readonly ILogger<HomeUserController> _logger;

        public HomeUserController(ILogger<HomeUserController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Views/AdminCategory/Index.cshtml
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Index";
}
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Category</h1>
          </div>
        </div>
      </div>
    </div>

<div class="card">
    <div class="card-body">
        <button class="btn btn-primary mb-3" data-toggle="modal" data-target="#modal-create">+ Add Category</button>
        <table class="table table-bordered table-hover" id="tableCategory">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Category Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <!--CREATE MODAL-->
    <div class="modal fade" id="modal-create" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm" class="addCategory">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="name">Category Name</label>
                            <input type="text" name="name" class="form-control" id="nameCategory"
                                placeholder="Enter category name">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnSave">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- EDIT MODAL -->
    <div class="modal fade" id="modal-edit" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Update Category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm" class="editCategory">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="nameEdit">Category Name</label>
                            <input type="text" name="name" class="form-control" id="nameEdit"
                                placeholder="Enter category name">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnEdit">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/AdminCategory2.js"></script>

Client/Views/AdminOrder/Index.cshtml
@{
    Layout = "_Adminlayout";
    ViewData["Title"] = "Index";
}
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Order</h1>
          </div>
        </div>
      </div>
    </div>

<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-hover" id="tableOrder">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Order Date</th>
                    <th>User</th>
                    <th>Detail Order</th>
                    <th>Payment Status</th>
                    <th>Delivery Status</th>
                    <th>Received Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <!--User Detail Modal -->
    <div class="modal fade" id="modalUserDetail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">User Detail</h1>
                </div>
                <div id="modalUserDetailx" class="modal-body container">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!--Order Detail Modal -->
    <div class="modal fade" id="modalOrderDetail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Order Detail</h1>
                </div>
                <div id="modalOrderDetailx" class="modal-body container">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!--Order Detail Modal -->
    <div class="modal fade" id="modalDeliveryDetail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delivery Detail</h1>
                </div>
                <div id="modalDeliveryDetailx" class="modal-body container">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- EDIT DELIVERY MODAL -->
    <div class="modal fade" id="modalDeliveryEdit" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Update Delivery Status</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="nameEdit">Delivery Status</label>
                            @*<select name="deliveryStatus" id="statusDeliveryEdit">
                                <option value="belumDikirim">Belum Dikirim</option>
                                <option value="sedangDikirim">Sedang Diproses</option>
                                <option value="sudahDikirim">Sudah Dikirim</option>
                            </select> *@            
                            <input type="text" name="deliveryStatus" class="form-control" id="statusDeliveryEdit"
                                   placeholder="Enter Delivery Status">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnDeliveryEdit" onclick="deliveryEdit()">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- EDIT ORDER MODAL -->
    <div class="modal fade" id="modalOrderEdit" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Update Delivery Status</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="paymentEdit">Payment Status</label>
                            @*<select name="paymentStatus" id="statusPaymentEdit">
                                <option value="belumDibayar">Belum Dibayar</option>
                                <option value="sudahDibayar">Sudah Dibayar</option>
                            </select>*@
                            <input type="text" name="paymentEdit" class="form-control" id="statusPaymentEdit"
                                   placeholder="Enter Payment Status" >
                        </div>
                        <div class="form-group">
                            <label for="nameEdit">Received Status</label>
                            @*<select name="receivedStatus" id="statusReceivedEdit">
                                <option value="belumDiterima">Belum Diterima</option>
                                <option value="sudahDiterima">Sudah Diterima</option>
                            </select>*@
                            <input type="text" name="nameEdit" class="form-control" id="statusReceivedEdit"
                                   placeholder="Enter Received Status">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnOrderEdit" onclick="orderEdit()">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/AdminOrder.js"></script>

Client/Views/AdminPayment/Index.cshtml
@{
    Layout = "_Adminlayout";
    ViewData["Title"] = "Index";
}
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Payment</h1>
          </div>
        </div>
      </div>
    </div>

<div class="card">
    <div class="card-body">
        <button class="btn btn-primary mb-3" data-toggle="modal" data-target="#modal-create">+ Add Payment</button>
        <table class="table table-bordered table-hover" id="tablePayment">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Payment Name</th>
                    <th>Payment Number</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <!--CREATE MODAL-->
    <div class="modal fade" id="modal-create" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Payment</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm" class="addPayment">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="name">Payment Name</label>
                            <input type="text" name="name" class="form-control" id="namePayment"
                                   placeholder="Enter Payment name">
                            <label for="name">Payment Number</label>
                            <input type="text" name="name" class="form-control" id="numberPayment"
                                   placeholder="Enter Payment number">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnSave" onclick="create()">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- EDIT MODAL -->
    <div class="modal fade" id="modal-edit" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Update Payment</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form id="quickForm">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="nameEdit">Payment Name</label>
                            <input type="text" name="name" class="form-control" id="nameEdit"
                                   placeholder="Enter Payment name">
                            <label for="name">Payment Number</label>
                            <input type="text" name="name" class="form-control" id="numberEdit"
                                   placeholder="Enter Payment number">
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnEdit">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/AdminPayment.js"></script>

Client/Views/AdminUser/Index.cshtml
@{
    Layout = "_Adminlayout";
    ViewData["Title"] = "Index";
}

<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">List User</h1>
          </div>
        </div>
      </div>
    </div>

<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-hover" id="tableUser">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Created Date</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<script src="~/js/AdminUser.js"></script>

Client/Views/Home/Forbidden.cshtml
@{
    Layout = "_AccountLayout";
    ViewData["Title"] = "Forbidden";
}

<div class="error-page">
    <h2 class="headline text-warning"> 500</h2>
    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>
        <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
        </p>
        <form class="search-form">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

Client/Views/Home/Index.cshtml
@{
    Layout = "_UserLayout";
    ViewData["Title"] = "Home";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
*@

<div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="text-center">
                    <h1 class="text-white">WELCOME</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
        <div class="section text-center">
            <h2 class="title">Your main section here</h2>
        </div>
    </div>
</div>

Client/Views/Home/NotFound.cshtml
@{
    Layout = "_AccountLayout";
    ViewData["Title"] = "Not Found";
}


<div class="error-page">
    <h2 class="headline text-warning"> 404</h2>
    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>
        <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
        </p>
        <form class="search-form">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

Client/Views/Home/Unauthorization.cshtml
@{
    Layout = "_AccountLayout";
    ViewData["Title"] = "Unauthorized";
}

<div class="error-page">
    <h2 class="headline text-warning"> 401</h2>
    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> Sorry! Access denied you are not admin!.</h3>
        <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
        </p>
        <form class="search-form">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

Client/Views/HomeUser/Index.cshtml
@{
    Layout = "_UserLayout";
    ViewData["Title"] = "Home";
}

<div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="text-center">
                    <h1 class="text-white">WELCOME</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
        <div class="section text-center">
            <h2 class="title">Welcome</h2>
        </div>
    </div>
</div>

Client/Views/Shared/_UserLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!doctype html>
<html lang="en">

<head>
    <title>@ViewBag.Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- Material Kit CSS -->
    <link href="~/lib/assets/css/material-kit.css?v=3.0.0" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-colvis-2.3.3/b-html5-2.3.3/datatables.min.css" />
</head>

<body>
    <!-- Navbar Transparent -->
    <nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3 navbar-transparent">
        <div class="container">
            <a class="navbar-brand  text-white " href="https://demos.creative-tim.com/material-kit/presentation" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
                Material Kit 2
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon mt-2">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
                <ul class="navbar-nav navbar-nav-hover ms-auto">
                    <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-6">
                        <a asp-controller="Product" asp-action="Index" class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="productLink">
                            <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                            Explore Products
                        </a>
                    </li>

                    <li class="nav-item dropdown dropdown-hover mx-2">
                        <a asp-controller="Order" asp-action="Index" class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="orderLink">
                            <i class="material-icons opacity-6 me-2 text-md">view_day</i>
                            Your Order(Placeholder)
                        </a>
                    </li>

                    <li class="nav-item dropdown dropdown-hover mx-2">
                        <a asp-controller="Profile" asp-action="Index" class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="profileLink">
                            <i class="material-icons opacity-6 me-2 text-md">article</i>
                            Profile
                        </a>
                    </li>
                    <li class="nav-item dropdown dropdown-hover mx-2">
                        <a href="Account/Login" class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="adminLoginLink">
                            <i class="material-icons opacity-6 me-2 text-md">article</i>
                            Admin
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->


    @RenderBody()

    <footer class="footer pt-5 mt-5">  
    </footer>
    <script src="~/lib/plugins/jquery/jquery.min.js"></script>
    <!--   Core JS Files   -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-colvis-2.3.3/b-html5-2.3.3/datatables.min.js"></script>
    <script src="~/lib/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/productUser.js"></script>
    <script src="~/js/order.js"></script>
    <script src="~/js/profile.js"></script>
</body>

</html>